public class ForecastPoint {
    
    public string time_x;
    public string summary;
    public string icon;
    public string nearestStormDistance;
    public string nearestStormBearing;
    public string precipIntensity;
    public string precipProbability;
    public string temperature;
    public string apparentTemperature;
    public string dewPoint;
    public string humidity;
    public string pressure;
    public string windSpeed;
    public string windGust;
    public string windBearing;
    public string cloudCover;
    public string uvIndex;
    public string visibility;
    public string ozone;
        
}